# config/packages/easy_admin.yaml
easy_admin:
    
    # Désactiver TOUS les assets
    design:
        assets: []
        favicon: null
    
    # Utiliser AssetMapper explicitement
    asset_mapper:
        enabled: true
    
    # Options pour désactiver les features
    options:
        use_asset_mapper: true
